### PR TITLE
Updated fuse-setup.js to log correctly when FUSE installation fails

### PR DESCRIPTION
**Pull request by reaktivo**
Hi, I've been trying to get the Hyperdrive Fuse setup to work, but I haven't been successful. I did noticed some small issue when debugging, in that the onerror method is not defined.

### CODE REVIEW

**Review by andrewosh — APPROVED** [review]
Thanks @reaktivo, broke this right before the release when I moved the hyperfuse import into the `run` command. Oops. Merging + releasing

**Comment by reaktivo** [comment]
@andrewosh Wow that was fast!

**Comment by andrewosh** [comment]
Published in 1.13.8 -- yeah want those errors to be clear! :)

Thanks a bunch for submitting this.

**Comment by andrewosh** [comment]
And also are you using Windows or Node 14? Those are the only things that are known to cause FUSE problems currently. If you're on Linux or OSX and Node 11, 12, or 13, then this setup failure might be a new issue for us, so any info you have would help.

**Comment by reaktivo** [comment]
@andrewosh Thanks for the heads up, I had been trying it with Node 10 on macOS and on Node 14 on Ubuntu 20. I'll switch both to Node 12.

I was about to ask @mafintosh, @pfrazee and you if you would be open to have hyperdrive be compatible with Node 10, if you you think it's an achievable goal and if you're open to contributions for it.

Is there any clue what's currently causing the issues on Node 14?

**Comment by andrewosh** [comment]
So the Node 14 issue is being tracked in #47. We're digging into that one today.

As for 10, it'd be a very straightforward change, but it'd touch all the CLI commands. I made the mistake of writing them with static class properties, which I didn't realize were unsupported in 10.

I'd figured since 10 is about to go into "Maintenance" LTS in a few days, people would be upgrading, but that might be wishful thinking. Totally open to the change.

**Pull request merged**
